enclave:
  spid:        # Service Provider ID
  certificate: # Service Provider Certificate
  key:         # Service Provider Key
  iasHost:     # IAS Host to talk to (testing or production)
  acceptGroupOutOfDate: # Whether to serve IAS responses with GROUP_OUT_OF_DATE instead of OK [true|false]
  instances:
   - mrenclave: # mrenclave value 1
     debug:     # Whether this is a debug or production enclave [true|false]
   - mrenclave: # mrenclave value 2
     debug:     # Whether this is a debug or production enclave [true|false]

signal:
  userToken:    # head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'
  serverToken:  # head -c 16 /dev/urandom | hexdump -ve '1/1 "%.2x"'

redis:
  masterName:   # Redis Sentinel master name
  sentinelUrls:
   - # Redis Sentinel host:port 1
   - # Redis Sentinel host:port 2

directory:
  initialCapacity:         # Directory hash table initial capacity (integer)
  minLoadFactor:           # Directory hash table minimum load factor (decimal in range [0, 1])
  maxLoadFactor:           # Directory hash table maximum load factor (decimal in range [0, 1])
  mapBuilderDns:           # DNS A record that contains peer snapshot servers for direct connection
  mapBuilderPort:          # Port peer snapshot servers use for direct connection
  mapBuilderLoadBalancer:  # Url for where to query for peer snapshots
  peerAuthenticationToken: # Token used to authenticate with a peer
  peerReadEligible:        # boolean on whether you should attempt to load from a peer or redis
  sqs:                     # SQS FIFO queue config for directory event replication from Signal-Server
    accessKey:             # AWS access key ID for replication SQS FIFO queue
    accessSecret:          # AWS access key secret for replication SQS FIFO queue
    queueUrl:              # URL for replication SQS FIFO queue
    queueRegion:           # AWS region for replication SQS FIFO queue
    queueProcessingEnabled # whether to process the SQS queue

limits:
  contactQueries:
    bucketSize:        # Leaky bucket size (# of contacts queried)
    leakRatePerMinute: # Leaky bucket rate per minute
  remoteAttestations:
    bucketSize:        # Leaky bucket size (# of remote attestations)
    leakRatePerMinute: # Leaky bucket rate per minute

metrics:
  reporters:
    - type:     json # wavefront metrics reporter
      hostname:      # wavefront endpoint hostname
      token:         # wavefront endpoint token
