#
# Azure Pipelines job to build the cds-enclave-builder docker image used to build cds enclaves.
#

jobs:
- job: docker_build_cds_enclave_builder
  displayName: docker build cds-enclave-builder
  pool:
    vmImage: ubuntu-18.04
  steps:
  - task: Docker@2
    displayName: docker login
    inputs:
      command:           login
      containerRegistry: signalbackupci-container-registry

  - script: docker pull signalbackupci.azurecr.io/signalbackupci:cds-enclave-builder || true
    displayName: docker pull

  - task: Docker@2
    displayName: docker build
    inputs:
      command:    build
      dockerfile: enclave/docker/Dockerfile
      arguments:  --build-arg UID=1000 --build-arg GID=1000 --cache-from signalbackupci.azurecr.io/signalbackupci:cds-enclave-builder
      repository: signalbackupci
      tags:       cds-enclave-builder

  - task: Docker@2
    displayName: docker push
    inputs:
      command:    push
      repository: signalbackupci
      tags:       cds-enclave-builder
